### ISSUE TITLE
초대코드 관리

### ISSUE THREAD

**Issue by jeongbaebang** [Come-On-App/Come-On-Frontend#158]
- [x] 모달 컴포넌트
- [x] 안내 문구
- [x] 초대 코드 
- [x] 버튼
- [x] 복사 로직
- [x] 사용자 UX (Haptics)
- [x] 서버에러 안내

---
![Group 716](https://github.com/Come-On-App/Come-On-Frontend/assets/57677452/cf465daf-a995-4682-a6ad-4ec658a89695)

**Comment by bananana0118** [comment]
굿입니당 bb
